stages:
  - test
  - npm
  - dev
  - production

coverage:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
  when: on_success
  script:
    - coverage run --source='courses' manage.py test
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

npm:
  image: node:6
  stage: npm
  script:
    - npm install
    - npm run build
  only:
    - dev
    - master

dev:
  image: ruby:2.6
  stage: dev
  environment:
    name: dev
    url: $DEV_URL
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_DEV --api-key=$HEROKU_API_KEY
  only:
    - dev

production:
  image: ruby:2.6
  stage: production
  environment:
    name: production
    url: $PRODUCTION_URL
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master