stages:
  - test
  - dev
  - production

coverage:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
  when: on_success
  script:
    - coverage run --source='courses' manage.py test
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

dev:
  image: ruby:2.6
  stage: dev
  environment:
    name: dev
    url: $DEV_URL
  script:
    - apt-get update
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y nodejs
    - apt-get install -y npm
    - npm install
    - ls
    - npm run build
    - ls
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_DEV --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - static/dist/
  only:
    - dev

production:
  image: ruby:2.6
  stage: production
  environment:
    name: production
    url: $PRODUCTION_URL
  script:
    - apt-get update
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y nodejs
    - apt-get install -y npm
    - npm install
    - ls
    - npm run build
    - ls
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_PRODUCTION --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - static/dist/
  only:
    - master